default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test-heroku

test:
  <<: *default
  database: test-heroku

production:
  #Set Prod Database here
  <<: *default
  database: d3532no0nemblb
  username: vjltcixvfrallo
  password: 155a144734d88979739fe2b909d381173dbf0e7cf5b18d74a2195cbd71fb466e
  host: ec2-54-75-224-100.eu-west-1.compute.amazonaws.com
